FROM maven:3.9.5-openjdk-22 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:22-jre-slim
COPY --from=build /target/library-management-0.0.1-SNAPSHOT.jar /app/library-management-0.0.1-SNAPSHOT.jar